name: openwrt-build

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 获取源码
        uses: actions/checkout@v4

      - name: "设置环境"
        run: |
          bash init.sh

      - name: "开始构建"
        run: |
          cd ./openwrt
          make world V=s -j$(nproc)

      - name: "上传固件"
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: ~/openwrt/bin/targets/
