name: openwrt-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "获取源码"
        uses: actions/checkout@v4

      - name: "开始构建OpenWRT镜像"
        run: |
          bash build.sh

      - name: "上传构建后固件"
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: openwrt/bin/targets/

      - name: "上传构建日志"
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: make.log
